
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: EMPLOYEEID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: student_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


  - name: third_model
    description: "A starter dbt model"
    columns:
      - name: NAMEDEST
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


